#!/bin/sh
#
# Starts pppd.
#

# Allow a few customizations from a config file

start() {
	PPPD_ARGS="$PPPD_ARGS call rlp_mobile_unicom_chinacom4g"

	echo -n "Starting pppd: "
	umask 077
	start-stop-daemon -S -q -p /var/run/pppd.pid \
		--exec /usr/sbin/pppd -- $PPPD_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo -n "Stopping dropbear sshd: "
	start-stop-daemon -K -q -p /var/run/pppd.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
