######################################################################
# Automatically generated by qmake (1.07a) Wed Dec 3 09:16:57 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
SOURCES += hello.cpp

CONFIG += release \
          warn_on \
          qt \
          thread 

